### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by ssbarnea** [CPVprogrammer/update-synology-index#1]
Sorry for raising a first bug only for this, but I would like to know if this works with current release of Synology.

I was hopping that someone will manage to create the missing glue between download station, filebot and media station. Can't wait to test it!

**Comment by CPVprogrammer** [comment]
Hi ssbarnea, thanks for view my script.

I found a bug with some characters in filenames or paths, and yes, it works with the current release of Synology.

**Comment by CPVprogrammer** [comment]
Hi, I have resolved the bug and added a log file in the config file.
If anyone found another issue with paths o filenames open a new issue with the path not working.
Thanks for using this script.
