### ISSUE TITLE
psql: FATAL:  role "admin" does not exist

### ISSUE THREAD

**Issue by ssbarnea** [CPVprogrammer/update-synology-index#2]
I run the script on my DSM, and I got this error:

```
# ./update-synoindex.sh
program executed at: 2015-08-29 13:49:17
psql: FATAL:  role "admin" does not exist
./update-synoindex.sh: return: line 349: Illegal number:
```

After bit of googling and reading  http://forum.synology.com/enu/viewtopic.php?f=232&t=79939 I discovered that the right way to connect to the database is with:

```
psql mediaserver postgresql
```

**Comment by CPVprogrammer** [comment]
yes, with postgres should work for everyone
thanks.
