### ISSUE TITLE
DSM 6.0 Error - Peer Authentication failed for user "postgres"

### ISSUE THREAD

**Issue by Goodbyemoff** [CPVprogrammer/update-synology-index#5]
I am getting the following error trying to run the script on DSM 6.0

```
psql: FATAL: Peer authentication failed for user "postgres"
/volume1/transfer/update-synoindex.sh: line 163: return: : numeric argument required
```

It seems that it is failing to authenticate for some reason.
I think it may be a setup issue. Do I need to change permissions for the user postgres?

**Comment by CPVprogrammer** [comment]
I found this solution:
http://stackoverflow.com/questions/18664074/getting-error-peer-authentication-failed-for-user-postgres-when-trying-to-ge

in /etc/postgresql there is a file named "pg_hba.conf" and you can change the method with these:
    trust - anyone who can connect to the server is authorized to access the database
    peer - use client's operating system user name as database user name to access it.
    md5 - password-base authentication

I use root for execute the script and my "pg_hba.conf" file is:
# TYPE  DATABASE        USER            ADDRESS                 METHOD
local       all                       postgres                                          peer map=pg_root
local       all                       all                                                    peer

I hope this solution help you.

**Comment by Goodbyemoff** [comment]
Problem solved. As mentioned, run the script as Root, admin is not sufficient. 

Thanks.
