### ISSUE TITLE
Does not work with break spaces in directories to treat

### ISSUE THREAD

**Issue by xaozai** [CPVprogrammer/update-synology-index#6]
This script does not work with break spaces in directories to treat.

Error: find: `"/volume1/video/TV': No such file or directory

Conf:
#directories to treat --> 0 recursive, 1 no recursive
0 /volume1/video/TV show/

**Comment by CPVprogrammer** [comment]
It should work now.

I tested with:
#directories to treat --> 0 recursive, 1 no recursive
0 /volume1/video/TV_show/
0 /volume1/video/show 2
0 /volume1/video/TV Shows/show 1/

Thanks.
